# Generated by Django 4.1 on 2023-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart_name", models.CharField(max_length=64, verbose_name="部门名称")),
                ("company", models.CharField(max_length=128, verbose_name="公司名称")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="员工姓名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("mobile", models.CharField(max_length=128, verbose_name="手机号")),
                (
                    "account",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="账户"
                    ),
                ),
            ],
        ),
    ]
