# Generated by Django 4.1 on 2023-12-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(null=True, verbose_name="创建时间"),
        ),
    ]
