# Generated by Django 4.1 on 2023-12-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_userinfo_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(1, "男"), (2, "女")], null=True, verbose_name="性别"
            ),
        ),
    ]
