# Generated by Django 4.1 on 2023-12-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_mobileaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileaccount",
            name="isdelect",
            field=models.SmallIntegerField(
                choices=[(0, "有效"), (1, "无效")], default=0, verbose_name="是否有效"
            ),
        ),
    ]
