# Generated by Django 4.1 on 2023-12-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_mobileaccount_isdelect"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, verbose_name="管理员姓名")),
                ("password", models.CharField(max_length=128, verbose_name="登录密码")),
            ],
        ),
    ]
