# Generated by Django 4.1 on 2024-01-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "一般"), (2, "中等"), (3, "紧急")],
                        default=1,
                        verbose_name="任务等级",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="任务标题")),
                ("remark", models.TextField(max_length=256, verbose_name="详细描述")),
                ("create_time", models.DateTimeField(null=True, verbose_name="创建时间")),
                (
                    "do_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.userinfo",
                        verbose_name="执行人",
                    ),
                ),
            ],
        ),
    ]
