# Generated by Django 4.1 on 2024-01-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="订单号")),
                ("tilte", models.CharField(max_length=128, verbose_name="货物名称")),
                ("price", models.CharField(max_length=32, verbose_name="价格")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "待支付"), (2, "已支付")], default=1, verbose_name="支付状态"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.admin",
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
