# Generated by Django 4.1 on 2024-01-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0009_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.admin",
                verbose_name="管理员",
            ),
        ),
    ]
