# Generated by Django 4.1 on 2024-01-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0011_admin_account"),
    ]

    operations = [
        migrations.RenameField(model_name="order", old_name="tilte", new_name="title",),
    ]
